# Cross-validation

## Splitting data manually

* Really manually, i.e., with separate files
* In code with one dataset (e.g., how homework has gone)

In [5]:
import pandas as pd

train_df = pd.read_csv('Urban land cover/training.csv')
train_df
#class is our target label

class  BrdIndx  Area  Round  Bright  Compact  ShpIndx  Mean_G  \
0         car      1.27    91   0.97  231.38     1.39     1.47  207.92   
1    concrete      2.36   241   1.56  216.15     2.46     2.51  187.85   
2    concrete      2.12   266   1.47  232.18     2.07     2.21  206.54   
3    concrete      2.42   399   1.28  230.40     2.49     2.73  204.60   
4    concrete      2.15   944   1.73  193.18     2.28     4.10  165.98   
..         ...      ...   ...    ...     ...      ...      ...     ...   
163       car      1.43    39   1.41  234.03     1.54     1.60  206.36   
164      soil      1.92   141   1.24  215.19     2.02     2.02  212.28   
165     grass      2.97   252   1.73  164.13     3.20     3.09  184.15   
166     grass      1.57   216   1.27  164.84     1.71     1.97  192.55   
167  concrete      2.12   836   0.88  232.84     1.78     2.52  202.39   

     Mean_R  Mean_NIR  ...  SD_NIR_140  LW_140  GLCM1_140  Rect_140  \
0    241.74    244.48  ...       26.18    2.00       0.50      0.85   
1    229.39    231.20  ...       22.29    2.25       0.79      0.55   
2    244.22    245.79  ...       15.59    2.19       0.76      0.74   
3    243.27    243.32  ...       13.51    3.34       0.82      0.74   
4    205.55    208.00  ...       15.65   50.08       0.85      0.49   
..      ...       ...  ...         ...     ...        ...       ...   
163  246.05    249.69  ...       55.92    1.73       0.65      0.81   
164  216.28    217.00  ...       18.91    3.49       0.88      0.67   
165  152.03    156.22  ...       33.52    2.02       0.86      0.71   
166  148.34    153.62  ...       24.49    1.13       0.76      0.85   
167  247.24    248.89  ...        7.84    1.52       0.76      0.24   

     GLCM2_140  Dens_140  Assym_140  NDVI_140  BordLngth_140  GLCM3_140  
0         6.29      1.67       0.70     -0.08             56    3806.36  
1         8.42      1.38       0.81     -0.09           1746    1450.14  
2         7.24      1.68       0.81     -0.07            566    1094.04  
3         7.44      1.36       0.92     -0.09           1178    1125.38  
4         8.15      0.23       1.00     -0.08           6232    1146.38  
..         ...       ...        ...       ...            ...        ...  
163       7.05      1.89       0.42     -0.10             66    2469.69  
164       7.88      1.44       0.82      0.06            990     824.01  
165       8.50      1.82       0.54      0.06            948     821.84  
166       7.75      2.11       0.30      0.09            254    1580.72  
167       7.16      0.74       0.49     -0.09           3020    1611.55  

[168 rows x 148 columns]

In [6]:
test_df = pd.read_csv('Urban land cover/testing.csv')
test_df
# class is our target label

class  BrdIndx  Area  Round  Bright  Compact  ShpIndx  Mean_G  \
0    concrete      1.32   131   0.81  222.74     1.66     2.18  192.94   
1      shadow      1.59   864   0.94   47.56     1.41     1.87   36.82   
2      shadow      1.41   409   1.00   51.38     1.37     1.53   41.72   
3        tree      2.58   187   1.91   70.08     3.41     3.11   93.13   
4     asphalt      2.60   116   2.05   89.57     3.06     3.02   73.17   
..         ...      ...   ...    ...     ...      ...      ...     ...   
502  building      1.36  3146   0.90  244.97     1.44     1.39  229.86   
503     grass      2.51   428   1.55  166.02     2.16     2.61  210.11   
504  concrete      2.45   659   1.38  219.30     1.68     2.53  189.64   
505  building      1.90    89   1.01  219.88     2.02     2.01  184.82   
506  building      2.48   155   1.68  225.15     2.57     2.69  192.61   

     Mean_R  Mean_NIR  ...  SD_NIR_140  LW_140  GLCM1_140  Rect_140  \
0    235.11    240.15  ...       31.15    5.04       0.80      0.58   
1     48.78     57.09  ...       12.01    3.70       0.52      0.96   
2     51.96     60.48  ...       18.75    3.09       0.90      0.63   
3     55.20     61.92  ...       27.67    6.33       0.89      0.70   
4     94.89    100.64  ...       32.05    1.01       0.83      0.75   
..      ...       ...  ...         ...     ...        ...       ...   
502  252.47    252.58  ...        7.58    1.51       0.63      0.84   
503  135.89    152.04  ...       18.91    1.14       0.86      0.67   
504  233.14    235.12  ...       14.67    2.21       0.74      0.78   
505  235.18    239.65  ...       37.11    5.26       0.75      0.85   
506  239.95    242.88  ...       10.50    3.92       0.71      0.85   

     GLCM2_140  Dens_140  Assym_140  NDVI_140  BordLngth_140  GLCM3_140  
0         8.56      0.82       0.98     -0.10           1512    1287.52  
1         7.01      1.69       0.86     -0.14            196    2659.74  
2         8.32      1.38       0.84      0.10           1198     720.38  
3         8.56      1.10       0.96      0.20            524     891.36  
4         8.62      2.08       0.08     -0.10            496    1194.76  
..         ...       ...        ...       ...            ...        ...  
502       6.85      1.96       0.47     -0.04            784    1911.96  
503       7.70      1.80       0.50      0.22           1020     801.65  
504       7.47      1.70       0.74     -0.09           2596    1243.03  
505       8.47      1.30       0.94     -0.12            726    1470.63  
506       6.74      1.52       0.89     -0.11            296    1991.25  

[507 rows x 148 columns]

Build our Decision Tree with 4 features

In [7]:
from sklearn import tree, metrics

model = tree.DecisionTreeClassifier(min_samples_leaf=10)
features = ['Area', 'Round', 'Bright', 'Compact']
train_X = train_df[features]
model.fit(train_X, train_df['class'])

test_X = test_df[features]
predictions = model.predict(test_X)
kappa = metrics.cohen_kappa_score(test_df['class'], predictions)
print('Test kappa:', kappa) # Note if we re-run it the results may differ slightly as is some randomness in CART

Test kappa: 0.5214255182731353


## Implementing 2-fold cross-validation

In [8]:
# Concatenate the train_df and test_df datasets into a single combined_df. 
# Verify that the length of the combined dataframe matches the sum of the individual lengths of train_df and test_df.
combined_df = pd.concat([train_df, test_df])
print(len(combined_df), len(train_df) + len(test_df))

675 675


In [29]:
# Now that we have the combined dataset, 
# Loop over 2 folds 
# Split the data into two halves (first_half and second_half)
# In the first fold (fold_num == 0), use first half of the data for training and the second half for testing.
# In the second fold (fold_num == 1), this is reversed: use the second half for training and the first half for testing.
# Don't forget to evaluate on test at each round with kappa and compute the avg kappa at the end.

# YOUR CODE HERE
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
kf = KFold(n_splits=2, shuffle=True)
kappas = []
scores = []
for fold_num, (train_index, test_index) in enumerate(kf.split(combined_df)):
    if fold_num == 0:
        train_df = combined_df.iloc[train_index]
        test_df = combined_df.iloc[test_index]
    else:
        train_df = combined_df.iloc[test_index]
        test_df = combined_df.iloc[train_index]
    model = tree.DecisionTreeClassifier(min_samples_leaf=10)
    model.fit(train_df[features], train_df['class'])
    score = cross_val_score(model, train_df[features], train_df['class'], cv=kf)
    scores.append(score)
    predictions = model.predict(test_df[features])
    kappa = metrics.cohen_kappa_score(test_df['class'], predictions)
    kappas.append(kappa)

np.mean(kappas)

0.5132893229087443

### Check class counts and accuracy for one class

In [24]:
combined_df['class'].value_counts()

class
building     122
concrete     116
grass        112
tree         106
shadow        61
asphalt       59
car           36
soil          34
pool          29
Name: count, dtype: int64

In [25]:
# Opened CSV file, and observed there is a space after the labels for some reason -.-
test_y = test_df['class']
building_predictions = predictions == 'building ' # boolean True for rows that model's predictions are the class 'building '
building_predictions
building_labels = test_y == 'building ' # boolean True for rows that ground-truth label are the class 'building '
building_labels
building_kappa = metrics.cohen_kappa_score(building_labels, building_predictions)
building_kappa

0.508142919066196

In [26]:
# Overall kappa (across all classes)
metrics.cohen_kappa_score(predictions, test_y)

0.6007006680788659

## 10-fold in sklearn

In [16]:
from sklearn import model_selection
import numpy as np  

In [17]:
# First version, we will loop manually, illustrate how data indices are selected
xval = model_selection.KFold(10, shuffle=True) 
all_kappas = []  
all_predictions = []  

for train_i, test_i in xval.split(combined_df):
    # For each fold, the fold is split into training indices (train_i) and test indices (test_i).
    print('New cross-validation fold')
    print(train_i[:10])
    print(test_i[:10])
    print(len(train_i), len(test_i))

    # Find data rows from combined_df dataframe for each fold based on the indices train_i and test_i.
    train_df = combined_df.iloc[train_i]
    test_df = combined_df.iloc[test_i]

    # Features and labels
    train_X = train_df[features]
    test_X = test_df[features]
    train_y = train_df['class']
    test_y = test_df['class']

    # Build DT on fold train set, eval on fold test set
    model = tree.DecisionTreeClassifier(min_samples_leaf=10)
    model.fit(train_X, train_y)
    predictions = model.predict(test_X)
    kappa = metrics.cohen_kappa_score(test_y, predictions)
    print('Kappa:', kappa)
    all_predictions.extend(predictions)  # Save for averaging
    all_kappas.append(kappa)             # Save for averaging

print('Kappa mean:', np.mean(all_kappas))  # Average
print('Kappa SD:', np.std(all_kappas))     # Standard deviation

New cross-validation fold
[ 0  2  5  6  7  8  9 10 11 12]
[ 1  3  4 18 27 50 51 57 62 83]
607 68
Kappa: 0.501138375917025
New cross-validation fold
[ 0  1  2  3  4  6  7  8  9 10]
[ 5 14 26 32 42 45 54 58 80 84]
607 68
Kappa: 0.4534036674202462
New cross-validation fold
[0 1 2 3 4 5 6 7 8 9]
[ 24  36  38  55  60  77  88  93 123 125]
607 68
Kappa: 0.49938650306748467
New cross-validation fold
[ 0  1  2  3  4  5  6  7  9 10]
[ 8 12 21 22 33 35 39 48 49 52]
607 68
Kappa: 0.4670846394984326
New cross-validation fold
[ 0  1  3  4  5  6  7  8  9 10]
[  2  11  16  28  30  34  41  63  78 102]
607 68
Kappa: 0.604551201011378
New cross-validation fold
[0 1 2 3 4 5 6 7 8 9]
[19 20 23 25 29 44 68 79 82 98]
608 67
Kappa: 0.5197770108839925
New cross-validation fold
[ 0  1  2  3  4  5  7  8  9 10]
[  6  17  37  40  61  65  70  71  99 109]
608 67
Kappa: 0.5882202304737516
New cross-validation fold
[ 0  1  2  3  4  5  6  8  9 10]
[  7  15  43  56  59  73  89  97 100 103]
608 67
Kappa: 0.57516512549537

## Using cross_validate

Useful and simpler for some future homework!

In [18]:
# Repeating example using cross_validate; makes life easier, and helps prevent mistakes!
from sklearn import neighbors

model = tree.DecisionTreeClassifier(min_samples_leaf=10)
# model = neighbors.KNeighborsClassifier(3)
X = combined_df[features]
y = combined_df['class']
xval = model_selection.KFold(10, shuffle=True)

# Create custom scorer 
# A scorer is a wrapper around an arbitrary metric or loss function that is called with signature scorer(estimator, X, y_true, **kwargs).
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.make_scorer.html
scorer = metrics.make_scorer(metrics.cohen_kappa_score)

# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html
results = model_selection.cross_validate(model, X, y, cv=xval, scoring=scorer, return_train_score=True)
results

# {
#   'fit_time': array([...]),      # Time taken to fit the model for each fold
#   'score_time': array([...]),    # Time taken to score the model for each fold
#   'test_score': array([...]),    # Cohen's Kappa scores on the test set for each fold
#   'train_score': array([...])    # Cohen's Kappa scores on the training set for each fold
# }


{'fit_time': array([0.00803757, 0.00399899, 0.00399685, 0.00400782, 0.00403404,
        0.0039916 , 0.00399518, 0.00401521, 0.00700378, 0.00500011]),
 'score_time': array([0.0026114 , 0.00394821, 0.00199962, 0.00199056, 0.00199986,
        0.00200152, 0.0020113 , 0.00260019, 0.00565767, 0.0030117 ]),
 'test_score': array([0.54203043, 0.51329243, 0.59693752, 0.49329359, 0.69098712,
        0.58631335, 0.59743992, 0.53520041, 0.57583751, 0.44819341]),
 'train_score': array([0.69790369, 0.69788818, 0.6797876 , 0.69896104, 0.67231555,
        0.69124188, 0.69848085, 0.70931052, 0.68573266, 0.70989726])}

In [19]:
print(results['test_score'])
print(results['train_score'])

print('Test kappa mean:', results['test_score'].mean())
print('Test kappa SD:', results['test_score'].std())
print('Train kappa mean:', results['train_score'].mean())
print('Train kappa SD:', results['train_score'].std())

[0.54203043 0.51329243 0.59693752 0.49329359 0.69098712 0.58631335
 0.59743992 0.53520041 0.57583751 0.44819341]
[0.69790369 0.69788818 0.6797876  0.69896104 0.67231555 0.69124188
 0.69848085 0.70931052 0.68573266 0.70989726]
Test kappa mean: 0.5579525697481794
Test kappa SD: 0.06394922489283968
Train kappa mean: 0.6941519228870457
Train kappa SD: 0.011446024811243738


### Try `min_samples_leaf` down to 1 to observe overfitting.

In [20]:
# (very optional) We can also make a Dataframe for results, e.g., do some post-analysis or save them in a file.
results_df = pd.DataFrame(results)
results_df

fit_time  score_time  test_score  train_score
0  0.008038    0.002611    0.542030     0.697904
1  0.003999    0.003948    0.513292     0.697888
2  0.003997    0.002000    0.596938     0.679788
3  0.004008    0.001991    0.493294     0.698961
4  0.004034    0.002000    0.690987     0.672316
5  0.003992    0.002002    0.586313     0.691242
6  0.003995    0.002011    0.597440     0.698481
7  0.004015    0.002600    0.535200     0.709311
8  0.007004    0.005658    0.575838     0.685733
9  0.005000    0.003012    0.448193     0.709897

## Getting scores of one specific class
We need to revert to manual loops if we need k-fold scores for one specific class :(

Very useful though, for example when data are imbalanced

In [21]:
xval = model_selection.KFold(10, shuffle=True)
specific_kappas = []
for train_i, test_i in xval.split(combined_df):
    train_df = combined_df.iloc[train_i]
    test_df = combined_df.iloc[test_i]
    model = tree.DecisionTreeClassifier(min_samples_leaf=10)
    model.fit(train_df[features], train_df['class'])
    predictions = model.predict(test_df[features])
    specific_predictions = predictions == 'building '
    specific_y = test_df['class'] == 'building '
    kappa = metrics.cohen_kappa_score(specific_y, specific_predictions)
    print('Kappa:', kappa)
    specific_kappas.append(kappa)

print('Kappa mean:', np.mean(specific_kappas))
print('Kappa SD:', np.std(specific_kappas))

# Then change from building to "pool ", the least common class, and observe kappa

Kappa: 0.7979197622585439
Kappa: 0.6406869220607663
Kappa: 0.31658291457286425
Kappa: 0.5603448275862069
Kappa: 0.6406869220607663
Kappa: 0.231357552581262
Kappa: 0.39639639639639634
Kappa: 0.4931921331316187
Kappa: 0.5491251682368775
Kappa: 0.12812812812812802
Kappa mean: 0.47544207270134303
Kappa SD: 0.19576644295252843
