# Cross-validation

## Splitting data manually

* Really manually, i.e., with separate files
* In code with one dataset (e.g., how homework has gone)

In [2]:
import pandas as pd

train_df = pd.read_csv('Urban land cover/training.csv')
train_df
#class is our target label

class  BrdIndx  Area  Round  Bright  Compact  ShpIndx  Mean_G  \
0         car      1.27    91   0.97  231.38     1.39     1.47  207.92   
1    concrete      2.36   241   1.56  216.15     2.46     2.51  187.85   
2    concrete      2.12   266   1.47  232.18     2.07     2.21  206.54   
3    concrete      2.42   399   1.28  230.40     2.49     2.73  204.60   
4    concrete      2.15   944   1.73  193.18     2.28     4.10  165.98   
..         ...      ...   ...    ...     ...      ...      ...     ...   
163       car      1.43    39   1.41  234.03     1.54     1.60  206.36   
164      soil      1.92   141   1.24  215.19     2.02     2.02  212.28   
165     grass      2.97   252   1.73  164.13     3.20     3.09  184.15   
166     grass      1.57   216   1.27  164.84     1.71     1.97  192.55   
167  concrete      2.12   836   0.88  232.84     1.78     2.52  202.39   

     Mean_R  Mean_NIR  ...  SD_NIR_140  LW_140  GLCM1_140  Rect_140  \
0    241.74    244.48  ...       26.18    2.00       0.50      0.85   
1    229.39    231.20  ...       22.29    2.25       0.79      0.55   
2    244.22    245.79  ...       15.59    2.19       0.76      0.74   
3    243.27    243.32  ...       13.51    3.34       0.82      0.74   
4    205.55    208.00  ...       15.65   50.08       0.85      0.49   
..      ...       ...  ...         ...     ...        ...       ...   
163  246.05    249.69  ...       55.92    1.73       0.65      0.81   
164  216.28    217.00  ...       18.91    3.49       0.88      0.67   
165  152.03    156.22  ...       33.52    2.02       0.86      0.71   
166  148.34    153.62  ...       24.49    1.13       0.76      0.85   
167  247.24    248.89  ...        7.84    1.52       0.76      0.24   

     GLCM2_140  Dens_140  Assym_140  NDVI_140  BordLngth_140  GLCM3_140  
0         6.29      1.67       0.70     -0.08             56    3806.36  
1         8.42      1.38       0.81     -0.09           1746    1450.14  
2         7.24      1.68       0.81     -0.07            566    1094.04  
3         7.44      1.36       0.92     -0.09           1178    1125.38  
4         8.15      0.23       1.00     -0.08           6232    1146.38  
..         ...       ...        ...       ...            ...        ...  
163       7.05      1.89       0.42     -0.10             66    2469.69  
164       7.88      1.44       0.82      0.06            990     824.01  
165       8.50      1.82       0.54      0.06            948     821.84  
166       7.75      2.11       0.30      0.09            254    1580.72  
167       7.16      0.74       0.49     -0.09           3020    1611.55  

[168 rows x 148 columns]

In [3]:
test_df = pd.read_csv('Urban land cover/testing.csv')
test_df
# class is our target label

class  BrdIndx  Area  Round  Bright  Compact  ShpIndx  Mean_G  \
0    concrete      1.32   131   0.81  222.74     1.66     2.18  192.94   
1      shadow      1.59   864   0.94   47.56     1.41     1.87   36.82   
2      shadow      1.41   409   1.00   51.38     1.37     1.53   41.72   
3        tree      2.58   187   1.91   70.08     3.41     3.11   93.13   
4     asphalt      2.60   116   2.05   89.57     3.06     3.02   73.17   
..         ...      ...   ...    ...     ...      ...      ...     ...   
502  building      1.36  3146   0.90  244.97     1.44     1.39  229.86   
503     grass      2.51   428   1.55  166.02     2.16     2.61  210.11   
504  concrete      2.45   659   1.38  219.30     1.68     2.53  189.64   
505  building      1.90    89   1.01  219.88     2.02     2.01  184.82   
506  building      2.48   155   1.68  225.15     2.57     2.69  192.61   

     Mean_R  Mean_NIR  ...  SD_NIR_140  LW_140  GLCM1_140  Rect_140  \
0    235.11    240.15  ...       31.15    5.04       0.80      0.58   
1     48.78     57.09  ...       12.01    3.70       0.52      0.96   
2     51.96     60.48  ...       18.75    3.09       0.90      0.63   
3     55.20     61.92  ...       27.67    6.33       0.89      0.70   
4     94.89    100.64  ...       32.05    1.01       0.83      0.75   
..      ...       ...  ...         ...     ...        ...       ...   
502  252.47    252.58  ...        7.58    1.51       0.63      0.84   
503  135.89    152.04  ...       18.91    1.14       0.86      0.67   
504  233.14    235.12  ...       14.67    2.21       0.74      0.78   
505  235.18    239.65  ...       37.11    5.26       0.75      0.85   
506  239.95    242.88  ...       10.50    3.92       0.71      0.85   

     GLCM2_140  Dens_140  Assym_140  NDVI_140  BordLngth_140  GLCM3_140  
0         8.56      0.82       0.98     -0.10           1512    1287.52  
1         7.01      1.69       0.86     -0.14            196    2659.74  
2         8.32      1.38       0.84      0.10           1198     720.38  
3         8.56      1.10       0.96      0.20            524     891.36  
4         8.62      2.08       0.08     -0.10            496    1194.76  
..         ...       ...        ...       ...            ...        ...  
502       6.85      1.96       0.47     -0.04            784    1911.96  
503       7.70      1.80       0.50      0.22           1020     801.65  
504       7.47      1.70       0.74     -0.09           2596    1243.03  
505       8.47      1.30       0.94     -0.12            726    1470.63  
506       6.74      1.52       0.89     -0.11            296    1991.25  

[507 rows x 148 columns]

Build our Decision Tree with 4 features

In [4]:
from sklearn import tree, metrics

model = tree.DecisionTreeClassifier(min_samples_leaf=10)
features = ['Area', 'Round', 'Bright', 'Compact']
train_X = train_df[features]
model.fit(train_X, train_df['class'])

test_X = test_df[features]
predictions = model.predict(test_X)
kappa = metrics.cohen_kappa_score(test_df['class'], predictions)
print('Test kappa:', kappa) # Note if we re-run it the results may differ slightly as is some randomness in CART

Test kappa: 0.5214255182731353


## Implementing 2-fold cross-validation

In [5]:
# Concatenate the train_df and test_df datasets into a single combined_df. 
# Verify that the length of the combined dataframe matches the sum of the individual lengths of train_df and test_df.
combined_df = pd.concat([train_df, test_df])
print(len(combined_df), len(train_df) + len(test_df))

675 675


In [6]:
# Now that we have the combined dataset, 
# Loop over 2 folds 
# Split the data into two halves (first_half and second_half)
# In the first fold (fold_num == 0), use first half of the data for training and the second half for testing.
# In the second fold (fold_num == 1), this is reversed: use the second half for training and the first half for testing.
# Don't forget to evaluate on test at each round with kappa and compute the avg kappa at the end.
avg_kappa = 0
for fold_num in range(2):
    halfway = int(len(combined_df) / 2)
    first_half = combined_df[:halfway]
    second_half = combined_df[halfway:]
    if fold_num == 0:
        train_X = first_half[features]
        train_y = first_half['class']
        test_X = second_half[features]
        test_y = second_half['class']
    else:
        train_X = second_half[features]
        train_y = second_half['class']
        test_X = first_half[features]
        test_y = first_half['class']
    model = tree.DecisionTreeClassifier(min_samples_leaf=10)
    model.fit(train_X, train_y)
    predictions = model.predict(test_X)
    kappa = metrics.cohen_kappa_score(test_y, predictions)
    avg_kappa += kappa
    print('Fold', fold_num, 'kappa =', kappa)
print('Avg kappa', avg_kappa/2)

Fold 0 kappa = 0.5328939904912182
Fold 1 kappa = 0.5141627241162258
Avg kappa 0.5235283573037219


### Check class counts and accuracy for one class

In [7]:
combined_df['class'].value_counts()

class
building     122
concrete     116
grass        112
tree         106
shadow        61
asphalt       59
car           36
soil          34
pool          29
Name: count, dtype: int64

In [8]:
# Opened CSV file, and observed there is a space after the labels for some reason -.-
building_predictions = predictions == 'building ' # boolean True for rows that model's predictions are the class 'building '
building_predictions
building_labels = test_y == 'building ' # boolean True for rows that ground-truth label are the class 'building '
building_labels
building_kappa = metrics.cohen_kappa_score(building_labels, building_predictions)
building_kappa

0.508151414464491

In [30]:
# Overall kappa (across all classes)
metrics.cohen_kappa_score(predictions, test_y)

0.5141627241162258

## 10-fold in sklearn

In [31]:
from sklearn import model_selection
import numpy as np  

In [33]:
# First version, we will loop manually, illustrate how data indices are selected
xval = model_selection.KFold(10, shuffle=True) 
all_kappas = []  
all_predictions = []  

for train_i, test_i in xval.split(combined_df):
    # For each fold, the fold is split into training indices (train_i) and test indices (test_i).
    print('New cross-validation fold')
    print(train_i[:10])
    print(test_i[:10])
    print(len(train_i), len(test_i))

    # Find data rows from combined_df dataframe for each fold based on the indices train_i and test_i.
    train_df = combined_df.iloc[train_i]
    test_df = combined_df.iloc[test_i]

    # Features and labels
    train_X = train_df[features]
    test_X = test_df[features]
    train_y = train_df['class']
    test_y = test_df['class']

    # Build DT on fold train set, eval on fold test set
    model = tree.DecisionTreeClassifier(min_samples_leaf=10)
    model.fit(train_X, train_y)
    predictions = model.predict(test_X)
    kappa = metrics.cohen_kappa_score(test_y, predictions)
    print('Kappa:', kappa)
    all_predictions.extend(predictions)  # Save for averaging
    all_kappas.append(kappa)             # Save for averaging

print('Kappa mean:', np.mean(all_kappas))  # Average
print('Kappa SD:', np.std(all_kappas))     # Standard deviation

New cross-validation fold
[ 0  1  2  3  4  5  6  7 10 11]
[  8   9  37  47  82  87 104 119 122 130]
607 68
Kappa: 0.5073694728953286
New cross-validation fold
[0 1 2 3 4 5 6 7 8 9]
[11 14 23 24 25 38 40 55 63 83]
607 68
Kappa: 0.6260801256873527
New cross-validation fold
[ 0  1  3  4  5  6  8  9 11 12]
[ 2  7 10 16 21 32 44 49 50 51]
607 68
Kappa: 0.5746810107580685
New cross-validation fold
[ 0  1  2  3  4  6  7  8  9 10]
[ 5 12 18 22 33 39 43 45 57 61]
607 68
Kappa: 0.5636550308008214
New cross-validation fold
[0 1 2 3 4 5 6 7 8 9]
[19 29 30 41 42 53 54 56 59 64]
607 68
Kappa: 0.4516129032258065
New cross-validation fold
[ 0  1  2  3  5  6  7  8  9 10]
[  4  36  58  88 102 131 157 160 161 163]
608 67
Kappa: 0.7146659568804898
New cross-validation fold
[ 0  2  3  4  5  6  7  8  9 10]
[  1  13  60  68  76  77  78  81 101 106]
608 67
Kappa: 0.3834355828220859
New cross-validation fold
[0 1 2 3 4 5 6 7 8 9]
[15 20 26 27 28 46 62 65 72 79]
608 67
Kappa: 0.5113310758009899
New cross-valida

## Using cross_validate

Useful and simpler for some future homework!

In [34]:
# Repeating example using cross_validate; makes life easier, and helps prevent mistakes!
from sklearn import neighbors

model = tree.DecisionTreeClassifier(min_samples_leaf=10)
# model = neighbors.KNeighborsClassifier(3)
X = combined_df[features]
y = combined_df['class']
xval = model_selection.KFold(10, shuffle=True)

# Create custom scorer 
# A scorer is a wrapper around an arbitrary metric or loss function that is called with signature scorer(estimator, X, y_true, **kwargs).
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.make_scorer.html
scorer = metrics.make_scorer(metrics.cohen_kappa_score)

# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html
results = model_selection.cross_validate(model, X, y, cv=xval, scoring=scorer, return_train_score=True)
results

# {
#   'fit_time': array([...]),      # Time taken to fit the model for each fold
#   'score_time': array([...]),    # Time taken to score the model for each fold
#   'test_score': array([...]),    # Cohen's Kappa scores on the test set for each fold
#   'train_score': array([...])    # Cohen's Kappa scores on the training set for each fold
# }


{'fit_time': array([0.0097611 , 0.00332975, 0.00256705, 0.0023191 , 0.00216103,
        0.00214386, 0.00195193, 0.00196624, 0.00183177, 0.00194407]),
 'score_time': array([0.00259709, 0.00128508, 0.00107169, 0.00096512, 0.0009408 ,
        0.00092292, 0.00101113, 0.00073195, 0.00068426, 0.00090003]),
 'test_score': array([0.5443299 , 0.62813821, 0.5225677 , 0.52028219, 0.58808682,
        0.47492163, 0.5569955 , 0.619023  , 0.56885457, 0.54374018]),
 'train_score': array([0.69086399, 0.69402929, 0.69423174, 0.70345634, 0.68874635,
        0.6890703 , 0.69276256, 0.69136569, 0.69451074, 0.68584912])}

In [35]:
print(results['test_score'])
print(results['train_score'])

print('Test kappa mean:', results['test_score'].mean())
print('Test kappa SD:', results['test_score'].std())
print('Train kappa mean:', results['train_score'].mean())
print('Train kappa SD:', results['train_score'].std())

[0.5443299  0.62813821 0.5225677  0.52028219 0.58808682 0.47492163
 0.5569955  0.619023   0.56885457 0.54374018]
[0.69086399 0.69402929 0.69423174 0.70345634 0.68874635 0.6890703
 0.69276256 0.69136569 0.69451074 0.68584912]
Test kappa mean: 0.556693970136809
Test kappa SD: 0.04429500673932326
Train kappa mean: 0.6924886110893111
Train kappa SD: 0.004511539668001688


### Try `min_samples_leaf` down to 1 to observe overfitting.

In [37]:
# (very optional) We can also make a Dataframe for results, e.g., do some post-analysis or save them in a file.
results_df = pd.DataFrame(results)
results_df

fit_time  score_time  test_score  train_score
0  0.009761    0.002597    0.544330     0.690864
1  0.003330    0.001285    0.628138     0.694029
2  0.002567    0.001072    0.522568     0.694232
3  0.002319    0.000965    0.520282     0.703456
4  0.002161    0.000941    0.588087     0.688746
5  0.002144    0.000923    0.474922     0.689070
6  0.001952    0.001011    0.556996     0.692763
7  0.001966    0.000732    0.619023     0.691366
8  0.001832    0.000684    0.568855     0.694511
9  0.001944    0.000900    0.543740     0.685849

## Getting scores of one specific class
We need to revert to manual loops if we need k-fold scores for one specific class :(

Very useful though, for example when data are imbalanced

In [41]:
xval = model_selection.KFold(10, shuffle=True)
specific_kappas = []
for train_i, test_i in xval.split(combined_df):
    train_df = combined_df.iloc[train_i]
    test_df = combined_df.iloc[test_i]
    model = tree.DecisionTreeClassifier(min_samples_leaf=10)
    model.fit(train_df[features], train_df['class'])
    predictions = model.predict(test_df[features])
    specific_predictions = predictions == 'building '
    specific_y = test_df['class'] == 'building '
    kappa = metrics.cohen_kappa_score(specific_y, specific_predictions)
    print('Kappa:', kappa)
    specific_kappas.append(kappa)

print('Kappa mean:', np.mean(specific_kappas))
print('Kappa SD:', np.std(specific_kappas))

# Then change from building to "pool ", the least common class, and observe kappa

Kappa: 0.5251396648044693
Kappa: 0.20788530465949817
Kappa: 0.4716981132075472
Kappa: 0.482608695652174
Kappa: 0.46571428571428575
Kappa: 0.5614545454545454
Kappa: 0.44830741079597436
Kappa: 0.763807285546416
Kappa: 0.5750528541226215
Kappa: 0.31673665266946616
Kappa mean: 0.4818404812626998
Kappa SD: 0.14149407601359765
